# default config
# /Applications/AeroSpace.app/Contents/Resources/default-config.toml

# General
config-version = 2
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30

# Run Sketchybar together with AeroSpace
# sketchybar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = ['exec-and-forget sketchybar']
# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Tiles
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

persistent-workspaces = ["1", "2", "3", "Q", "W", "E"]
# no workspace change on mode change
on-mode-changed = []

[key-mapping]
preset = 'qwerty'


[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 20
outer.bottom = 20
outer.top = 30
outer.right = 20


[mode.main.binding]
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-semicolon = 'mode service'

cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-q = 'workspace Q'
alt-w = 'workspace W'
alt-e = 'workspace E'

alt-rightSquareBracket = 'workspace next'
alt-leftSquareBracket = 'workspace prev'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-q = 'move-node-to-workspace Q'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-e = 'move-node-to-workspace E'

alt-shift-space = 'layout floating tiling'

alt-shift-r = [
    'reload-config',
    'exec-and-forget afplay /System/Library/Sounds/Glass.aiff'
]
# alt-shift-p = "exec-and-forget osascript -e 'display alert \"Task Done\" message \"Check it now\"'"

alt-r = 'mode resize'

alt-shift-s = 'exec-and-forget screencapture -i -c'

[mode.resize.binding]
minus = 'resize smart -50'
equal = 'resize smart +50'
alt-m = 'mode main'

[workspace-to-monitor-force-assignment]
# Top monitor
1 = 'secondary'
2 = 'secondary'
3 = 'secondary'
# Main monitor
Q = 'main'
W = 'main'
E = 'main'


# set apps for workspace
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace 1'


[[on-window-detected]]
if.app-id = 'com.jetbrains.WebStorm'
run = 'move-node-to-workspace Q'

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace W'


[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace E'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace E'


# floating apps
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'



# Docs
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                   sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift









